// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HTPSSystem.Entities;

[Table("Customer")]
[Index("Email", Name = "IX_CustomerEmail", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int CustomerID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string ContactNumber { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    [NotMapped]
    public string FullName { get { return LastName + ", " + FirstName; } }
}