// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HTPSSystem.Entities;

[Table("Product")]
public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string ModelNumber { get; set; }

    public bool Discontinued { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DiscontinuedDate { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}