// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ProgramSystemLibrary.Entities;

namespace ProgramSystemLibrary.DAL;

public partial class StarTEDContext : DbContext
{
    public StarTEDContext(DbContextOptions<StarTEDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Program> Programs { get; set; }

    public virtual DbSet<ProgramCourse> ProgramCourses { get; set; }

    public virtual DbSet<School> Schools { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<Program>(entity =>
        {
            entity.HasKey(e => e.ProgramID).HasName("PK_dbo.Programs");

            entity.HasOne(d => d.SchoolCodeNavigation).WithMany(p => p.Programs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.Programs_dbo.Schools_SchoolCode");
        });

        modelBuilder.Entity<ProgramCourse>(entity =>
        {
            entity.HasKey(e => e.ProgramCourseID).HasName("PK_dbo.ProgramCourses");

            entity.HasOne(d => d.Program).WithMany(p => p.ProgramCourses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.ProgramCourses_dbo.Programs_ProgramID");
        });

        modelBuilder.Entity<School>(entity =>
        {
            entity.HasKey(e => e.SchoolCode).HasName("PK_dbo.Schools");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}